apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: helloworldappreconciler.v0.0.1
spec:
  version: 0.0.1
  maintainers:
    - name: Juan Zuriaga
      email: jzuriaga@redhat.com
  maturity: alpha
  customresourcedefinitions:
    owned:
    - kind: HelloWorldApp
      name: helloworldapps.apps.example.com
      version: v1alpha1
  displayName: Hello World App Java operator
  capabilities: Seamless Upgrades
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
        serviceAccountName: helloworld-operator-operator
      deployments:
      - name: helloworld-operator-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/version: 0.0.1-SNAPSHOT
              app.kubernetes.io/name: helloworld-operator-operator
          template:
            metadata:
              annotations:
                app.quarkus.io/commit-id: 971245d1664eb282b75b85ff851a9b71c093c459
                app.quarkus.io/build-timestamp: 2022-03-11 - 06:41:15 +0000
                prometheus.io/scrape: "true"
                prometheus.io/path: /q/metrics
                prometheus.io/port: "8080"
                prometheus.io/scheme: http
              labels:
                app.kubernetes.io/version: 0.0.1-SNAPSHOT
                app.kubernetes.io/name: helloworld-operator-operator
            spec:
              containers:
              - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: quay.io/jzuriaga/helloworld-java-operator:v0.0.1beta1-java
                imagePullPolicy: Always
                livenessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/live
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
                name: helloworld-operator-operator
                ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
                readinessProbe:
                  failureThreshold: 3
                  httpGet:
                    path: /q/health/ready
                    port: 8080
                    scheme: HTTP
                  initialDelaySeconds: 0
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 10
              serviceAccountName: helloworld-operator-operator
      permissions:
      - rules:
        - apiGroups:
          - apps.example.com
          resources:
          - HelloWorldApp
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
          - update
        serviceAccountName: helloworld-operator-operator
      - rules:
        - apiGroups:
          - apps.example.com
          resources:
          - helloworldapps
          - helloworldapps/status
          verbs:
          - get
          - list
          - watch
          - create
          - delete
          - patch
          - update
        serviceAccountName: helloworld-operator-operator
    strategy: deployment
  installModes:
  - supported: true
    type: AllNamespaces
  - supported: true
    type: OwnNamespace
